/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated/labels'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedTracksRouteImport } from './routes/_authenticated/tracks'
import { Route as AuthenticatedArtistsIndexRouteImport } from './routes/_authenticated/artists.index'
import { Route as AuthenticatedArtistsNameRouteImport } from './routes/_authenticated/artists.$name'
import { Route as AuthenticatedCratesIndexRouteImport } from './routes/_authenticated/crates.index'
import { Route as AuthenticatedCratesCrateIdRouteImport } from './routes/_authenticated/crates.$crateId'
import { Route as AuthenticatedLabelsLabelIdRouteImport } from './routes/_authenticated/labels_.$labelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTracksRoute = AuthenticatedTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArtistsIndexRoute =
  AuthenticatedArtistsIndexRouteImport.update({
    id: '/artists/',
    path: '/artists/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArtistsNameRoute =
  AuthenticatedArtistsNameRouteImport.update({
    id: '/artists/$name',
    path: '/artists/$name',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCratesIndexRoute =
  AuthenticatedCratesIndexRouteImport.update({
    id: '/crates/',
    path: '/crates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCratesCrateIdRoute =
  AuthenticatedCratesCrateIdRouteImport.update({
    id: '/crates/$crateId',
    path: '/crates/$crateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabelsLabelIdRoute =
  AuthenticatedLabelsLabelIdRouteImport.update({
    id: '/labels_/$labelId',
    path: '/labels/$labelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/tracks': typeof AuthenticatedTracksRoute
  '/artists/$name': typeof AuthenticatedArtistsNameRoute
  '/crates/$crateId': typeof AuthenticatedCratesCrateIdRoute
  '/labels/$labelId': typeof AuthenticatedLabelsLabelIdRoute
  '/artists/': typeof AuthenticatedArtistsIndexRoute
  '/crates/': typeof AuthenticatedCratesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/tracks': typeof AuthenticatedTracksRoute
  '/artists/$name': typeof AuthenticatedArtistsNameRoute
  '/crates/$crateId': typeof AuthenticatedCratesCrateIdRoute
  '/labels/$labelId': typeof AuthenticatedLabelsLabelIdRoute
  '/artists': typeof AuthenticatedArtistsIndexRoute
  '/crates': typeof AuthenticatedCratesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/labels': typeof AuthenticatedLabelsRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/tracks': typeof AuthenticatedTracksRoute
  '/_authenticated/artists/$name': typeof AuthenticatedArtistsNameRoute
  '/_authenticated/crates/$crateId': typeof AuthenticatedCratesCrateIdRoute
  '/_authenticated/labels_/$labelId': typeof AuthenticatedLabelsLabelIdRoute
  '/_authenticated/artists/': typeof AuthenticatedArtistsIndexRoute
  '/_authenticated/crates/': typeof AuthenticatedCratesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/labels'
    | '/radar'
    | '/tracks'
    | '/artists/$name'
    | '/crates/$crateId'
    | '/labels/$labelId'
    | '/artists/'
    | '/crates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/labels'
    | '/radar'
    | '/tracks'
    | '/artists/$name'
    | '/crates/$crateId'
    | '/labels/$labelId'
    | '/artists'
    | '/crates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/discover'
    | '/_authenticated/labels'
    | '/_authenticated/radar'
    | '/_authenticated/tracks'
    | '/_authenticated/artists/$name'
    | '/_authenticated/crates/$crateId'
    | '/_authenticated/labels_/$labelId'
    | '/_authenticated/artists/'
    | '/_authenticated/crates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labels': {
      id: '/_authenticated/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracks': {
      id: '/_authenticated/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof AuthenticatedTracksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artists/': {
      id: '/_authenticated/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof AuthenticatedArtistsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artists/$name': {
      id: '/_authenticated/artists/$name'
      path: '/artists/$name'
      fullPath: '/artists/$name'
      preLoaderRoute: typeof AuthenticatedArtistsNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crates/': {
      id: '/_authenticated/crates/'
      path: '/crates'
      fullPath: '/crates/'
      preLoaderRoute: typeof AuthenticatedCratesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crates/$crateId': {
      id: '/_authenticated/crates/$crateId'
      path: '/crates/$crateId'
      fullPath: '/crates/$crateId'
      preLoaderRoute: typeof AuthenticatedCratesCrateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labels_/$labelId': {
      id: '/_authenticated/labels_/$labelId'
      path: '/labels/$labelId'
      fullPath: '/labels/$labelId'
      preLoaderRoute: typeof AuthenticatedLabelsLabelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedTracksRoute: typeof AuthenticatedTracksRoute
  AuthenticatedArtistsNameRoute: typeof AuthenticatedArtistsNameRoute
  AuthenticatedCratesCrateIdRoute: typeof AuthenticatedCratesCrateIdRoute
  AuthenticatedLabelsLabelIdRoute: typeof AuthenticatedLabelsLabelIdRoute
  AuthenticatedArtistsIndexRoute: typeof AuthenticatedArtistsIndexRoute
  AuthenticatedCratesIndexRoute: typeof AuthenticatedCratesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedLabelsRoute: AuthenticatedLabelsRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedTracksRoute: AuthenticatedTracksRoute,
  AuthenticatedArtistsNameRoute: AuthenticatedArtistsNameRoute,
  AuthenticatedCratesCrateIdRoute: AuthenticatedCratesCrateIdRoute,
  AuthenticatedLabelsLabelIdRoute: AuthenticatedLabelsLabelIdRoute,
  AuthenticatedArtistsIndexRoute: AuthenticatedArtistsIndexRoute,
  AuthenticatedCratesIndexRoute: AuthenticatedCratesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
